# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

function distinct_terms_of_length(n)
    distinct_terms = []
    for a=2:n
        for b=2:n
            value = BigInt(a)^b
            if !(value in distinct_terms)
                push!(distinct_terms, value)
            end
        end
    end

    return distinct_terms
end

println("The number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 is: ", length(distinct_terms_of_length(100)))